#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/yapdb
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: 1712wonwoo
#  jpa:
#    properties:
#      hibernate:
#        default_batch_fetch_size: 100
#        format_sql: true
#    open-in-view: false
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: create


spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        format_sql: true
        jdbc:
          batch_size: 100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yapdb.c7uknqplmcnk.ap-northeast-2.rds.amazonaws.com:3306/yaptrava?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999&rewriteBatchedStatements=true
#    url: jdbc:mysql://localhost:3306/yaptrava?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: yapyap
    password: 1712wonwoo