spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/yapdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1712wonwoo
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    open-in-view: false
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create